##################################################################################
# Cloudify Script built in types and plugins definitions.
##################################################################################

plugins:
    script:
        executor: central_deployment_agent
        source: https://github.com/vcloudair/cloudify-script-plugin/archive/1.2.1m5.zip
