##################################################################################
# Cloudify Script built in types and plugins definitions.
##################################################################################

plugins:
    script:
        executor: host_agent
        source: https://github.com/vcloudair/cloudify-script-plugin/archive/1.2.1-build.zip
