##################################################################################
# Cloudify Script built in types and plugins definitions.
##################################################################################

plugins:
    script:
        executor: central_deployment_agent
        source: https://github.com/Cloudify-PS/cloudify-script-plugin/archive/1.4walle.zip
        package_name: cloudify-wallescript-plugin
        package_version: '1.4walle'
