##################################################################################
# Cloudify Script built in types and plugins definitions.
##################################################################################

plugins:
    script:
        executor: central_deployment_agent
        source: https://github.com/0lvin/cloudify-script-plugin/archive/1.4-build.zip
        package_name: cloudify-script-plugin
        package_version: '1.4score'
